@exclude http://a.ligatus.com/*
@exclude http://trk.helios.ligatus.com/*
@exclude http://a248.e.akamai.net/*
@exclude http://ad-emea.doubleclick.net/*
@exclude http://ad2.adfarm1.adition.com/*
@exclude http://adimg.uimserv.net/*
@exclude http://advideo.uimserv.net/*
@exclude http://adx.ligadx.com/*
@exclude http://ams1.ib.adnxs.com/*
@exclude http://cdn.adnxs.com/*
@exclude http://code.createjs.com/*
@exclude http://d.ligatus.com/*
@exclude http://de.ioam.de/*
@exclude http://games.web.de/*
@exclude http://h.ligatus.com/*
@exclude http://i.ligatus.com/*
@exclude http://i0.gmx.net/*
@exclude http://imagesrv.adition.com/*
@exclude http://img.ui-portal.de//*
@exclude http://img.ui-portal.de/*
@exclude http://madclient.uimserv.net/*
@exclude http://n37.hal9000.redintelligence.net/*
@exclude http://pagead2.googlesyndication.com/*
@exclude http://pagead2.googlesyndication.com/*
@exclude http://pixelbox.uimserv.net/*
@exclude http://rtax.criteo.com/*
@exclude http://track.webgains.com/*
@exclude http://trk.helios.ligatus.com/
@exclude http://uim.tifbs.net/
@exclude http://wa.ui-portal.de/gmx/*
@exclude http://www.extraenergie.com/*
@exclude http://x.ligatus.com/*
@exclude https://ad.zanox.com/*
@exclude https://cdn.contentspread.net/*
@exclude https://games.web.de/*
@exclude https://gum.criteo.com/*
@exclude https://i-ssl.ligatus.com/*
@exclude https://i-ssl.ligatus.com/*
@exclude https://ib.adnxs.com/*
@exclude https://track.webgains.com/*
@exclude https://www.palmers.at/*
@exclude https://x.bidswitch.net/*
